### ISSUE TITLE
pages 我配置了好久没搞定！大神有咩有快捷点的方法？

### ISSUE THREAD

**Issue by maikebing** [twang2218/gitlab-ce-zh#13]

**Comment by twang2218** [comment]
Pages 需要配合 CI/CD，因此需要配置 Runner，比如下面的 `docker-compose.yml` 的例子：

```yml
version: '2'
services:
    gitlab:
        image: 'twang2218/gitlab-ce-zh:8.17.2'
        restart: unless-stopped
        hostname: 'git.example.com'
        environment:
            TZ: 'Asia/Shanghai'
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://git.example.com'
                pages_external_url 'http://pages.git.example.com'
                gitlab_rails['time_zone'] = 'Asia/Shanghai'
                gitlab_rails['gitlab_shell_ssh_port'] = 2222
        ports:
            - '80:80'
            - '443:443'
            - '2222:22'
        volumes:
            - config:/etc/gitlab
            - data:/var/opt/gitlab
            - logs:/var/log/gitlab
    runner:
        image: 'gitlab/gitlab-runner:latest'
        restart: unless-stopped
        volumes:
            - runner-config:/etc/gitlab-runner
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    config:
    data:
    logs:
    runner-config:
```

然后进入 Runner 配置页面，取得需要的 URL 以及 token，并在 runner 中配置：

```bash
docker-compose exec runner gitlab-runner register
```

根据提示填写。

另外还有两点需要注意：

- DNS 上要配置好泛域名解析 (*.pages.git.example.com)
- 官方镜像缺了 `unzip`，需要进入镜像单独安装，否则会出 `pages:deploy failed` 错误。稍后我会更新汉化的镜像把这个装上。
