### ISSUE TITLE
10.5.1，当时运行环境是mac，现在切换到centos7.4，起不来了

### ISSUE THREAD

**Issue by yangjiandong** [twang2218/gitlab-ce-zh#57]
启动 docker-compose.yml
```
version: '2'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:10.5.1'
      restart: unless-stopped
      # hostname: 'gitlab.example.com'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          # external_url 'http://gitlab.example.com'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
          # 比如下面的电子邮件的配置：
          # gitlab_rails['smtp_enable'] = true
          # gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
          # gitlab_rails['smtp_port'] = 465
          # gitlab_rails['smtp_user_name'] = "xxxx@xx.com"
          # gitlab_rails['smtp_password'] = "password"
          # gitlab_rails['smtp_authentication'] = "login"
          # gitlab_rails['smtp_enable_starttls_auto'] = true
          # gitlab_rails['smtp_tls'] = true
          # gitlab_rails['gitlab_email_from'] = 'xxxx@xx.com'
      ports:
        - '3000:80'
        # - '443:443'
        # - '22:22'
      volumes:
        - ./config:/etc/gitlab
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
volumes:
    config:
    data:
    logs:
```

现在安装都 centos7.4，把卷数据也考上去了，一直在启动，察看 `docker logs containerid`
```
error: could not open /var/opt/gitlab/.ssh/authorized_keys: Permission denied @ rb_sysopen - /var/opt/gitlab/.ssh/authorized_keys
```
